# Generated by Django 5.2.3 on 2025-06-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteshub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
