# Generated by Django 5.2.3 on 2025-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteshub', '0002_remove_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(default='TEMP-0001', max_length=20, unique=True),
        ),
    ]
