# Generated by Django 5.2.3 on 2025-06-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteshub', '0003_alter_customuser_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='uploaded_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
