# Generated by Django 5.2.3 on 2025-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteshub', '0004_notes_is_approved_notes_uploaded_by_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='uploaded_by_teacher',
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
